name: antria_mitra_mobile
description: "Antri Mitra Mobile"
publish_to: "none"
environment:
  sdk: ">=3.3.4 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  day_picker: ^2.2.0
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.2
  flutter_dotenv: ^5.1.0
  flutter_expandable_fab: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_timer_countdown: ^1.0.7
  fluttertoast: ^8.2.5
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  sqflite_sqlcipher: ^3.1.0+1
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  mocktail: ^0.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true,
  image_path: "assets/images/antria_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env
